### ISSUE TITLE
fancy reusing fabric8 apps?

### ISSUE THREAD

**Issue by jstrachan** [desdrury/k8sdc#3]
I stumbled on k8sdc on twitter today; looks interesting! 

I just thought I'd mention we've been working on something very similar called [fabric8](http://fabric8.io/); we've lots of the microservices you might want to reuse in k8sdc.  e.g. we've currently got:
- [management](http://fabric8.io/guide/management.html) we've a console, logging (Elasticsearch, Kibana, fluentd), metrics/alerting (prometheus / grafana2)
- [CI / CD](http://fabric8.io/guide/cdelivery.html) with Jenkins, Nexus, Gerrit, Sonarqube, Gogs/Gitlab and Taiga with a nice UI for creating new projects, importing projects from git, attaching CD pipelines and [visualising environments and pipelines](https://medium.com/fabric8-io/watching-your-project-move-through-its-cd-pipeline-and-environments-with-a-deep-holistic-18c24c092e2) etc.
- [Chaos Monkey](http://fabric8.io/guide/chaosMonkey.html)
- [ChatOps integration of all the above](http://fabric8.io/guide/chat.html)

All of the above are available using [helm](http://fabric8.io/guide/helm.html) to install things on the CLI; or you can use the OpenShift V3 CLI as we release OpenShift templates for all the microservices; or use the web console to just run what you want.

I just thought I'd give you a heads up. Feel free to [ping us](http://fabric8.io/community/) if you need help using any of our microservices. We should be able to expose them to k8sdc however you like so if you have a preferred file format / location of OpenShift Templates / Kubernetes resources it should be pretty easy to generate what you need from any fabric8 release - ideally automatically.

**Comment by desdrury** [comment]
Hey James,

Thanks for the heads up!  I had fabric8 on my radar but mistakenly thought it was exclusively Java components.  I didn't realise you guys had built so many additional capabilities or that you had such tight integration with Kubernetes / Openshift.  I've spent a bit of time today looking around the documentation today and the possibilities definitely excite me.  

I'm going to be chilling for a while over the Xmas period.  My wife told me to ;-)  But I'm definitely going to be investigating and playing around with fabric8 soon.  If you don't mind I'll probably ping you sometime in the new year.

Thanks.

**Comment by jstrachan** [comment]
@desdrury no worries! Its a common misconception that folks think fabric8 is Java centric. To be fair in 1.x it was pretty Java centric; but since version 2.x we re-architected everything on top of docker / kubernetes / openshift so that any pod/service can be any language/runtime/framework. We're increasingly using more and more nodejs and golang (e.g. the console is HTML5 + a go back end). 

Though we could do with making more demos using non-Java projects ;) e.g. nodejs / golang.

The current Java only feature is the new project wizard from templates; which so far only supports maven archetypes; we can support projects created via openshift's S2I mechanism now; or can import projects via git and then associate a Jenkins workflow with them. Right now [our Jenkins workflow library](http://fabric8.io/guide/jenkinsWorkflowLibrary.html) only has Maven examples but hopefully very soon we'll have some nodejs examples (and golang ideally too!). Would love to add other languages/runtimes to the wizards so its easy for folks to spin up projects using any kind of template; e.g. maybe a [Yeoman based wizard](https://github.com/fabric8io/fabric8/issues/5505).

The main tool to install / upgrade apps in environments inside CD has been maven up to now but we're hoping that [helm](http://fabric8.io/guide/helm.html) can be the polyglot approach which is a single binary written in go lang. Maybe one day `helm`-like functionality could be merged into `oc` or `kubectl` upstream too. Certainly there's a need to store versioned `charts` (in helm speak) or 'resources' (Services, Replication Controllers, Deployments  / Deployment Configs et al) so that its easy to move forward/back in a specific environment inside CD; which so far the helm / git approach seems pretty nice. With Maven we'd used the approach of storing all versions of resources inside a maven repository; which is what we do for all our kubernetes/openshift resources right now. e.g. [here's a distro](http://repo1.maven.org/maven2/io/fabric8/devops/distro/distro/) of the main devops resources - or you can consume them [individually](http://repo1.maven.org/maven2/io/fabric8/devops/apps/).

Incidentally we've been creating OpenShift Templates for all the microservices in fabric8 for now as there's a need for parameterisation as you install things (user/pwds, domain names or other configurations); hopefully when [Config Map](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/configmap.md) becomes a thing upstream in kubernetes & OpenShift we can look to moving more towards that instead which would mean we'd be able to generate regular Kubernetes resources that refer to Config Map instead. Plus I'm hoping we can add a nice custom UI to help folks configure the Config Map to help installing things. (e.g. if we can associate via annotations a JSON Schema for a specific Config Map, the hawtio-forms2 we use can generate a nice UI automatically which can be customized as needed!).

Anyway, thanks for your message - have a great chill (its my last day hacking this year too ;). Happy (Holidays | Christmas | New Year) and looking forward to touching base next year!

**Comment by jstrachan** [comment]
@desdrury BTW one other thing I meant to mention was CD; we've been having great success with [Jenkins Workflow](https://github.com/jenkinsci/workflow-plugin) for CD; though have had all kinds of fun and games trying to figure out the best way to use it with Jenkins Docker Workflow and Kubernetes; particularly with volumes, secrets & Service Accounts.

After much experimentation we've hit on the ideal combination: [kubernetes-workflow](https://github.com/fabric8io/kubernetes-workflow) which lets you combine all the best bits from Jenkins Workflow, Docker Workflow and Kubernetes; so you can reuse Secrets, Persistent Volumes, Service Accounts and Pods while using Jenkins workflow and docker images etc. 

You can then define your `Jenkinsfile` per project using any commands in any docker images you wish; so this works great for java, nodejs, golang, ruby, python et al
